# Generated by Django 2.0.9 on 2018-10-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
